# Generated by Django 4.1 on 2022-08-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'carrito', 'verbose_name_plural': 'carritos'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'artículo', 'verbose_name_plural': 'artículos'},
        ),
    ]
