# Generated by Django 4.1 on 2022-08-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'cuenta', 'verbose_name_plural': 'cuentas'},
        ),
    ]
