# Generated by Django 4.1 on 2022-08-29 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=100, verbose_name='Dirección principal')),
                ('address_line_2', models.CharField(blank=True, max_length=100, verbose_name='Dirección secundaria')),
                ('profile_picture', models.ImageField(blank=True, upload_to='userprofile', verbose_name='Profile picture')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='País')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
