# Generated by Django 4.1 on 2022-08-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'perfil de usuario', 'verbose_name_plural': 'perfil de usuarios'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='userprofile', verbose_name='Ávatar'),
        ),
    ]
